# Copyright Tandem Diabetes Care, Inc. 2023. All rights reserved.
# Github Action for whenever a PR is created
# codecov.yml
# @author alux Jan 25, 2023

# Used by Codecov
# Establishes our Codecov rules
codecov:
  token: 4b4b2f35-5879-406b-afcb-03c8031b6ef3

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flags:
  mobilebolus:
    paths:
      - app/src/main/java/com/tandemdiabetes/codecovpoc/mobilebolus/MobilebolusUtility.kt
  fullcontrol:
    paths:
      - app/src/main/java/com/tandemdiabetes/codecovpoc/fullcontrol/FullControlUtility.kt