# Copyright Tandem Diabetes Care, Inc. 2023. All rights reserved.
# Github Action for whenever a PR is created
# codecov.yml
# @author alux Jan 25, 2023

# Used by Codecov
# Establishes our Codecov rules
# CodecovPOC is the working repo with CodeCov <-> GitHub
codecov:
  token: 4b4b2f35-5879-406b-afcb-03c8031b6ef3

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
        threshold: 1%
      - name_prefix: patch-
        type: patch
        target: 90%